<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpDB.V2.Engine\SharpDB.V2.Engine.csproj" />
    <ProjectReference Include="..\SharpDB.V2.Infrastructure\SharpDB.V2.Infrastructure.csproj" />
  </ItemGroup>
</Project>
